concurrent = 1
check_interval = 0
shutdown_timeout = 0

[[runners]]
name = "My Docker Runner"
url = "http://192.168.0.130/"
token = "RZmthEY2DbKWBaoMavU5"
executor = "docker"
[runners.docker]
tls_verify = false
image = "mcr.microsoft.com/dotnet/sdk:6.0"
privileged = true
disable_cache = false
volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
[runners.cache]
[runners.cache.s3]
[runners.cache.gcs]
