version: 0.1
log:
  level: info
http:
  addr: 0.0.0.0:443
  tls:
    certificate: /certs/server.crt
    key: /certs/private.key
    insecure: true
storage:
  filesystem:
    rootdirectory: /var/lib/registry
