concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800


[[runners]]
  name = "Wallet Runner"
  url = "http://192.168.0.130:8080/"
  id = 1
  token = "7sYf1Kfb-U681Bkk3iHA"
  token_obtained_at = 2023-07-20T13:14:50Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    insecure = true
    image = "docker:stable"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    extra_hosts = ["host.docker.internal:host-gateway"]
    shm_size = 0
