version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: Gitlab
    restart: always
    ports:
      - '8080:80'     
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    environment:
      - REGISTRY_ENABLED=true
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=443
      - GITLAB_PORT=8080   
    networks:
      - gitlab-network

  jenkins:
    image: jenkins/jenkins:latest
    container_name: Jenkins
    restart: always
    ports:
      - '8081:8080'   
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: Gitlab-Runner
    restart: always
    volumes:
      - './config.toml:/etc/gitlab-runner/config.toml'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network
    privileged: true   
  
  docker-registry:
    image: registry:latest
    container_name: docker_registry
    restart: always
    ports:
      - '8443:443'    
    environment:
      - REGISTRY_CONFIG=/etc/docker/registry/config.yml
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    volumes:
      - ./registry:/var/lib/registry
      - ./certs:/certs
      - ./config.yml:/etc/docker/registry/config.yml:ro
      - ./auth:/auth
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge

volumes:
  jenkins_home:
