stages:
  - build
  - test
  - deploy

variables:
  DOCKER_REGISTRY_URL: 192.168.0.130:8443
  IMAGE_NAME: mywallet

services:
  - docker:dind

before_script:
  - mkdir -p $HOME/.docker
  - export DOCKER_TLS_CERTDIR=""

build:
  only:
    - master
  image: docker:latest
  script:
    - docker login -u Bookey -p Bookey_16 https://192.168.0.130:8443/
    - docker build -t 192.168.0.130:8443/mywallet .
    - docker push 192.168.0.130:8443/mywallet
  stage: build

test:
  stage: test
  services:
    - docker:dind
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  script:
    - dotnet test --no-restore
  dependencies:
    - build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u Bookey -p Bookey_16 https://192.168.0.130:8443/
    - docker pull 192.168.0.130:8443/mywallet
    - docker run -d --name my-wallet-container -p 80:80 192.168.0.130:8443/mywallet
  dependencies:
    - test

