
stages:

  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - dotnet build 


test_job:
  stage: test
  script:
    - dotnet test


deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project"
