image: docker:stable

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-app
  DOCKER_REGISTRY_URL: https://192.168.0.130:8443/

services:
  - docker:dind

before_script:
  - mkdir -p $HOME/.docker
  - export DOCKER_TLS_CERTDIR=""

build:
  only:
    - master
  script:
    - docker login -u Bookey -p Bookey_16 https://192.168.0.130:8443/
    - docker build -t bookey/my_app:latest .
    - docker push 192.168.0.130:8443/bookey/my-app:latest
  stage: build

test:
  stage: test
  services:
    - docker:dind
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  script:
    - dotnet test --no-restore
  dependencies:
    - build

deploy:
  stage: deploy
  services:
    - docker:dind
  variables:
    DEPLOY_PORT: 8888
  script:
    - docker login -u Bookey -p Bookey_16 $DOCKER_REGISTRY_URL
    - docker pull $DOCKER_REGISTRY_URL/bookey/my-app:latest
    - docker run -d --name my-app-container -p $DEPLOY_PORT:8888 $DOCKER_REGISTRY_URL/bookey/my-app:latest dotnet run --project E-Wallet.sln
  dependencies:
    - build
