stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - dotnet build E-Wallet/E-Wallet.csproj

test_job:
  stage: test
  script:
    - dotnet test E-Wallet/Wallet.Web.Tests/ControllerTests/AccManagerTest.csproj

deploy_job:
  stage: deploy
  script:
    - git remote set-url origin http://192.168.234.145/financial-solutions/digital-payment-solutions.git
    - echo "Deploying the project"
