image: docker:latest

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-app
  DOCKER_REGISTRY: 192.168.0.137:7000
  DOCKER_IMAGE_TAG: $CI_COMMIT_REF_SLUG
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://127.0.0.1:2375

build:
  stage: build
  services:
    - docker:19-dind
  script:
    - docker info
    - docker build -t $IMAGE_NAME .
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker tag $IMAGE_NAME:latest $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker push $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG

test:
  stage: test
  services:
    - docker:19-dind
  script:
    - docker info
    - dotnet test --no-restore --source https://api.nuget.org/v3/index.json
  dependencies:
    - build

deploy:
  stage: deploy
  services:
    - docker:19-dind
  variables:
    DEPLOY_PORT: 8888
  script:
    - docker info
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker pull $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run -d --name my-app-container -p $DEPLOY_PORT:8888 $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG dotnet run --project E-Wallet.sln
  dependencies:
    - build