image: docker:stable

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-app
  
services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - master
  before_script:
    - docker login http://localhost:7000/v2/ -u root -p htpassword
  script:
    - docker build -t http://localhost:7000/v2/E-Wallet:latest .
    - docker push http://localhost:7000/v2/E-Wallet:latest
  after_script:
    - docker logout http://localhost:7000/v2/
  stage: build
  tags:
    - docker

deploy:
  stage: deploy
  services:
    - docker:dind
  variables:
    DEPLOY_PORT: 8888
  script:
    - docker info
    - docker login --username root --password-stdin htpassword http://localhost:7000/v2/
    - docker pull http://localhost:7000/v2/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run -d --name my-app-container -p $DEPLOY_PORT:8888 http://localhost:7000/v2/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG dotnet run --project E-Wallet.sln
  dependencies:
    - build
