image: docker:stable

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-walletapp
  DOCKER_REGISTRY_URL: https://192.168.0.130:8443/
  HTPASSWD_FILE: ./auth/htpasswd

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - master
  script:
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL
    - docker build -t $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest .
    - docker push $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest
  stage: build
  tags:
    - docker

test:
  stage: test
  services:
    - docker:dind
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  script:
    - docker info
    - dotnet test --no-restore
  dependencies:
    - build

deploy:
  stage: deploy
  services:
    - docker:dind
  variables:
    DEPLOY_PORT: 8888
    HTPASSWD_CONTENT: $HTPASSWD_FILE  # Assign the htpasswd file content to the variable
  script:
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL
    - docker pull $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest
    - docker run -d --name my-walletapp-container -p $DEPLOY_PORT:8888 --env-file <(echo "$HTPASSWD_CONTENT") $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest dotnet run --project E-Wallet.sln
  dependencies:
    - build
