stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-wallet
  DOCKER_REGISTRY: 192.168.0.101:7000
  DOCKER_IMAGE_TAG: $CI_COMMIT_REF_SLUG

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet build -c Release --source https://api.nuget.org/v3/index.json
    - docker build -t $IMAGE_NAME .
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker tag $IMAGE_NAME:latest $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker push $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet test --no-restore --source https://api.nuget.org/v3/index.json

deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:6.0
  variables:
    DEPLOY_PORT: 8888
  script:
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker pull $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run -d --name my-app-container -p $DEPLOY_PORT:8888 $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG dotnet run --project E-Wallet.sln
