image: docker:stable

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-app
  DOCKER_REGISTRY_URL: https://192.168.0.130:8443/

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - master
  script:
    - docker login -u Bookey -p Bookey_16 https://192.168.0.130:8443/
    - docker build -t $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest .
    - docker push $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest
  stage: build
  tags:
    - docker

test:
  stage: test
  services:
    - docker:dind
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  script:
    - dotnet test --no-restore
  dependencies:
    - build

deploy:
  stage: deploy
  services:
    - docker:dind
  variables:
    DEPLOY_PORT: 8888
  script:
    - docker login -u Bookey -p Bookey_16 https://192.168.0.130:8443/
    - docker pull $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest
    - docker run -d --name my-app-container -p $DEPLOY_PORT:8888 $DOCKER_REGISTRY_URL/$IMAGE_NAME:latest dotnet run --project E-Wallet.sln
  dependencies:
    - build
