stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-wallet
  DOCKER_REGISTRY: 192.168.0.130:7000
  DOCKER_IMAGE_TAG: $CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://127.0.0.1:2375   # Add the DOCKER_HOST variable

build:
  stage: build
  image: gitlab/gitlab-runner:latest
  services:
    - docker:dind   # Add the DinD service
  script:
    - docker info   # Verify Docker connectivity
    - docker build -t $IMAGE_NAME .
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker tag $IMAGE_NAME:latest $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker push $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG

test:
  stage: test
  image: gitlab/gitlab-runner:latest
  services:
    - docker:dind   # Add the DinD service
  script:
    - docker info   # Verify Docker connectivity
    - dotnet test --no-restore --source https://api.nuget.org/v3/index.json

deploy:
  stage: deploy
  image: gitlab/gitlab-runner:latest
  services:
    - docker:19-dind   # Add the DinD service
  variables:
    DEPLOY_PORT: 8888
  script:
    - docker info   # Verify Docker connectivity
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker pull $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run -d --name my-app-container -p $DEPLOY_PORT:8888 $DOCKER_REGISTRY/E-Wallet/$IMAGE_NAME:$DOCKER_IMAGE_TAG dotnet run --project E-Wallet.sln
