version: "3.8"
services:
  db:
    image: postgres
    container_name: E-WalletDb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./app:/app/E-Wallet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: E-Wallet
    volumes:
      - .:/app/E-Wallet
    command: ["dotnet", "Wallet.Web.exe"]
    depends_on:
      - db
    ports:
      - "8080:80"

volumes:
  local_pgdata:
  pgadmin-data:
